name: .NET Tests and Deploy

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release -m

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Publish project
        run: dotnet  publish src/HomeAutomation/HomeAutomation.csproj --configuration Release -o publish_output -m --no-build

      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish_output
          path: publish_output
          retention-days: 7

      # --- Tag and Release ---
      - name: Bump version tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          tag_prefix: v

      - name: Get latest tag
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Create ZIP for GitHub Release
        run: |
          cd publish_output
          zip -r ../netdaemon.zip .

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          name: Release ${{ steps.get_tag.outputs.tag }}
          files: netdaemon.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Shutdown build server
        run: dotnet build-server shutdown

